export { default as MeFullImage } from './meFull.webp'
export { default as MeMinImage } from './meMin.webp'
export { default as cvBuilder_webp } from './cvBuilder_1.webp'
export { default as cvBuilder_gif } from './cvBuilder_2.gif'
export { default as kumoTask_webp } from './kumoTask_1.webp'
export { default as kumoTask_gif } from './kumoTask_2.gif'
