export { default as ChakraLogo } from './Chakra.webp'
export { default as ReactLogo } from './React.webp'
export { default as ZustandLogo } from './Zustand.webp'
export { default as kumoTaskLogo } from './min_logo.svg'
export { default as cvBuilderLogo } from './min.svg'
